name: Alemeno
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #UI
  shimmer: ^2.0.0
  flutter_animate: ^4.1.1+1
  fluttertoast: ^8.2.1

  #Network
  connectivity_plus: ^3.0.4
  dio: ^5.1.1

  #Storage
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.14

  #Device
  flutter_screenutil: ^5.7.0
  permission_handler: ^10.4.1
  flutter_svg: ^2.0.5
  easy_localization: ^3.0.2
  intl: ^0.18.0
  change_app_package_name: ^1.1.0
  camera: ^0.10.5+2
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  flutter_gen_runner:


flutter_gen:
    output: lib/gen/
    line_length: 80

    integrations:
      flutter_svg: true
      flare_flutter: true
      rive: true
      lottie: true

    fonts:
      outputs:
        class_name: Fonts
    colors:
      outputs:
        class_name: AppColors
      inputs:
        - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
        - assets/locales/
        - assets/images/
        - assets/icons/
        - assets/fonts/
        - assets/colors/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Andika
      fonts:
        - asset: assets/fonts/Andika-Bold.ttf
          weight: 700
        - asset: assets/fonts/Andika-Regular.ttf
          weight: 400
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne.ttf
